(define (problem hospital_battery_delivery)
  (:domain hospital_single_robot_battery)

  (:objects
    robot1 - robot
    elevator1 - elevator
    med1 med2 med3 med4 med5 med6 med7 med8 - medicine
    patient1 patient2 patient3 patient4 patient5 patient6 patient7 patient8 - patient
    robot_room storage room1_1 room1_2 room1_3 room1_4 room2_1 room2_2 room2_3 room2_4 - location
    floor0 floor1 floor2 - floor
  )

  (:init
    (robot_at robot1 robot_room)
    (elevator_at elevator1 floor0)
    (robot_available robot1)
    (elevator_available elevator1)
    (not (low_battery robot1))
    (not (battery_critical robot1))
    (= (robot_load robot1) 0.00)
    (= (total-cost) 0.00)
    (= (move_progress robot1) 0.00)
    (= (elevator_progress elevator1) 0.00)
    (= (robot_speed robot1) 0.50)
    (= (elevator_speed elevator1) 0.20)
    (= (battery_level robot1) 100.00)
    (= (battery_drain_rate robot1) 5.00)
    (= (battery_charge_rate robot1) 5.00)
    (= (low_battery_threshold) 40.00)
    (= (critical_battery_threshold) 20.00)

    (medicine_at med1 storage)
    (medicine_at med2 storage)
    (medicine_at med3 storage)
    (medicine_at med4 storage)
    (medicine_at med5 storage)
    (medicine_at med6 storage)
    (medicine_at med7 storage)
    (medicine_at med8 storage)
    (patient_at patient1 room1_1)
    (patient_at patient2 room1_2)
    (patient_at patient3 room1_3)
    (patient_at patient4 room1_4)
    (patient_at patient5 room2_1)
    (patient_at patient6 room2_2)
    (patient_at patient7 room2_3)
    (patient_at patient8 room2_4)
    (connected robot_room storage)
    (connected storage robot_room)
    (connected room1_1 room1_2) (connected room1_2 room1_1)
    (connected room1_2 room1_3) (connected room1_3 room1_2)
    (connected room1_3 room1_4) (connected room1_4 room1_3)
    (connected room2_1 room2_2) (connected room2_2 room2_1)
    (connected room2_2 room2_3) (connected room2_3 room2_2)
    (connected room2_3 room2_4) (connected room2_4 room2_3)
    (at_floor robot_room floor0)
    (at_floor storage floor0)
    (at_floor room1_1 floor1)
    (at_floor room1_2 floor1)
    (at_floor room1_3 floor1)
    (at_floor room1_4 floor1)
    (at_floor room2_1 floor2)
    (at_floor room2_2 floor2)
    (at_floor room2_3 floor2)
    (at_floor room2_4 floor2)
    (connected_floor floor0 floor1)
    (connected_floor floor1 floor0)
    (connected_floor floor1 floor2)
    (connected_floor floor2 floor1)
  )

  (:goal (and
    (medicine_at med1 room1_1)
    (medicine_at med2 room1_2)
    (medicine_at med3 room1_3)
    (medicine_at med4 room1_4)
    (medicine_at med5 room2_1)
    (medicine_at med6 room2_2)
    (medicine_at med7 room2_3)
    (medicine_at med8 room2_4)
    (robot_at robot1 robot_room)
    (not (battery_critical robot1))
  ))

  (:metric minimize (total-cost))
)